### ISSUE TITLE
Errors in o.0.5

### ISSUE THREAD

**Issue by Molodax** [custom-cards/group-card#15] opened 2021-06-10 11:32 UTC
There are two errors.
One "this.lastChild.setConfig is not a function" seems to be for a long time when some changes were introduced in homeassitant.
Another one "Unexpected token '{'" was newly introduced in v. 0.0.5

Logger: frontend.js.latest.202106030
Source: components/system_log/__init__.py:190
First occurred: June 8, 2021, 23:41:57 (12 occurrences)
Last logged: 11:38:44

https://xxx.xxx/hacsfiles/group-card/group-card.js:24:20 Uncaught TypeError: this.lastChild.setConfig is not a function
https://xxx.xxx/hacsfiles/group-card/group-card.js:54:17 Uncaught SyntaxError: Unexpected token '{'

**Comment by iantrich** [comment] 2021-06-10 21:55
Duplicate of #14

**Closed as completed by iantrich** 2021-06-10 21:55 UTC

**Comment by Molodax** [comment] 2021-06-11 10:30
Sorry but it is not a duplicate re: Uncaught TypeError: this.lastChild.setConfig is not a function
